// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrate/introspection はプールされていない直接接続を使う(Neonのpooler経由では
    // advisory lockやDDLが不安定なため)。07_人間作業チェックリスト.md A-3参照。
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
